version: "3.9"

services:
  logbot:
    build: .
    env_file: .env
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
      - CONTAINER_NAME=${CONTAINER_NAME}
      - LOG_NAME=${LOG_NAME}
      - LOG_REGEX=${LOG_REGEX}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./bot_monitor.py:/app/bot_monitor.py
    restart: unless-stopped
    container_name: btb_trace_bot