version: "3.9"

services:
  logbot:
    build: .
    env_file: .env
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
      - CONTAINER_NAME=${CONTAINER_NAME}
      - LOGGER_NAME=${LOGGER_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    container_name: btb_trace_bot